FORMAT: 1A
HOST: http://www.dealingroom.live

# Dealing Room
Dealing Room is a simple API allowing users to obtain information from the Dealing Room database.

## %5B/api/users/:userid%5D [/api/users/:userid]
### Obtaining single user's information  [GET]
+ Response 200 (application/json)

        {
            "username": "johndoe@gmail.com",
            "password": "*********",
            "displayName": "John Doe",
            "userPhoto": "www.dealingroom.com/user/01/img/photo.jpeg",
            "role": "customer"
        }
        
### Editing single user's information  [PUT]
+ Request (application/json)

        {
            "username": "johndoe@gmail.com",
            "password": "*********",
            "displayName": "Johnny",
            "userPhoto": "www.dealingroom.com/user/01/img/photo1.jpeg"
            "role": "customer",
            "isActive": true
        }

+ Response 201

## %5B/api/users%5D [/api/users]
### Adding new user [POST]
You can add additional users into the database using this action. It takes a JSON
object containing:
- username
- password
- displayName (optional)
- userPhoto (optional)
- FB accessToken (if Facebook login is used)
- role (bartender, server, manager or customer)

+ Request (application/json)

        {
            "username": "janedoe@gmail.com",
            "password": "********",
            "displayName": "Jane Doe",
            "userPhoto": "www.dealingroom.com/user/02/img/photo.jpeg",
            "role": "customer"
        }

+ Response 201 (application/json)

        {
            "users.id": 1,
            "username": "janedoe@gmail.com"
        }

## %5B/api/items/:itemid%5D [/api/items/:itemid]
### Obtaining single item's information  [GET]
+ Response 200 (application/json)

        {
            "id": 1,
            "itemName": "Asahi",
            "itemStock": 100,
            "categoryName": "Beer",
            "minimumPrice": 50.00,
            "currentPrice": 105.00,
            "itemPhoto": "www.dealingroom.com/public/img/asahi.jpeg",
            "itemDescription": "Asahi Super Dry was a direct result of extensive market research which indicated a consumer preference for a more palatable beer with less maltiness, relatively high alcohol content and a light aftertaste, that paired well with the changing Japanese diet. With this insight Asahi used its brewing knowledge to develop a beer with a crisp bite, refreshing taste and clear finish to satisfied this requirement."
        }
        
### Editing single item's information  [PUT]
+ Request (application/json)

        {
        "id": 1,
            "itemName": "Asahi",
            "itemStock": 100,
            "categoryName": "Beer",
            "minimumPrice": 50.00,
            "currentPrice": 110.00,
            "itemPhoto": "www.dealingroom.com/public/img/asahi.jpeg",
            "itemDescription": "Asahi Super Dry was a direct result of extensive market research which indicated a consumer preference for a more palatable beer with less maltiness, relatively high alcohol content and a light aftertaste, that paired well with the changing Japanese diet. With this insight Asahi used its brewing knowledge to develop a beer with a crisp bite, refreshing taste and clear finish to satisfied this requirement.",
            "isActive": true
        }

+ Response 201

## %5Bapi/items%5D [/api/items]
### Obtaining all item's information  [GET]
+ Response 200 (application/json)

        [
            {
                "categoryName": "Beer"
                "categoryPhoto": "www.dealingroom.com/public/img/beer.jpeg"
                {
                    "id": 1,
                    "itemName": "Asahi",
                    "itemStock": 100,
                    "categoryName": "Beer",
                    "minimumPrice": 50.00,
                    "currentPrice": 105.00,
                    "itemPhoto": "www.dealingroom.com/public/img/asahi.jpeg",
                    "itemDescription": "Asahi Super Dry was a direct result of extensive market research which indicated a consumer preference for a more palatable beer with less maltiness, relatively high alcohol content and a light aftertaste, that paired well with the changing Japanese diet. With this insight Asahi used its brewing knowledge to develop a beer with a crisp bite, refreshing taste and clear finish to satisfied this requirement."
                },
                {
                    "id": 2,
                    "itemName": "Heineken",
                    "itemStock": 100,
                    "categoryName": "Beer",
                    "minimumPrice": 45.00,
                    "currentPrice": 90.00,
                    "itemPhoto": "www.dealingroom.com/public/img/heineken.jpeg",
                    "itemDescription": "100% Barley malt, choice hops and pure water give this brew unsurpassed clarity."
                },
                    {
                    "id": 3,
                    "itemName": "Peroni",
                    "itemStock": 100,
                    "categoryName": "Beer",
                    "minimumPrice": 55.00,
                    "currentPrice": 10.00,
                    "itemPhoto": "www.dealingroom.com/public/img/Peroni.jpeg",
                    "itemDescription": "The original Italian lager. Peroni is the number one lager brand in Italy and has been for over one and a half centuries. This premium, clear, golden-yellow lager, with 4.7 ABV, is the result of the dedication to brewing of generations of the most qualified braumeisters."
                },
                {
                    "id": 4,
                    "itemName": "Stella Artois",
                    "itemStock": 100,
                    "categoryName": "Beer",
                    "minimumPrice": 60.00,
                    "currentPrice": 100.00,
                    "itemPhoto": "www.dealingroom.com/public/img/stellaartois.jpeg",
                    "itemDescription": "Stella Artois is one of the world’s best-selling beers and is enjoyed in more than 80 countries. Its full, characteristic flavour and high quality is assured through a superior brewing process and by using the finest ingredients available."
                }
            },
            {
                "categoryName": "Vodka"
                "categoryPhoto": "www.dealingroom.com/public/img/vodka.jpeg"
                {
                    "id": 51
                    "itemName" : "Grey Goose",
                    "itemStock" : 100,
                    "categoryName" : "Vodka",
                    "minimumPrice" : 100.00
                    "currentPrice" : 150.00,
                    "itemPhoto" : "www.dealingroom.com/public/img/greygoose.jpeg",
                    "itemDescription" : "From Cognac in France, this breakthrough wheat-based small-batch ultra-premium vodka has achieved global success and won a Platinum medal at the World Spirits Championship. Clean and fresh, with a smooth, creamy texture."
                },        
                {
                    "id": 52,
                    "itemName" : "Ketel One",
                    "itemStock" : 100,
                    "categoryName" : "Vodka",
                    "minimumPrice" : 95.00,
                    "currentPrice" : 120.00,
                    "itemPhoto" : "www.dealingroom.com/public/img/ketelone.jpeg",
                    "itemDescription" : "A meticulously crafted vodka from a Dutch distillery that has remained a family business for 10 generations since 1691. Introduced in the UK in 1999 after massive US success."
                }            
            },
            {
                "categoryName": "Gin"
                "categoryPhoto": "www.dealingroom.com/public/img/gin.jpeg"
                {
                    "id": 61
                    "itemName" : "Bombay Sapphire",
                    "itemStock" : 100,
                    "categoryName" : "Gin",
                    "minimumPrice" : 90.00
                    "currentPrice" : 130.00,
                    "itemPhoto" : "www.dealingroom.com/public/img/bombaysapphire.jpeg",
                    "itemDescription" : "Trendy younger sibling to Bombay Original, on whose recipe it is based (with a couple of extra botanicals). Credited with kickstarting gin's fashionability since its launch in 1987, Bombay Sapphire has become a truly iconic brand, with its distinctive blue bottle recognisable in bars the world over."
                },        
                {
                    "id": 52,
                    "itemName" : "Hendricks",
                    "itemStock" : 100,
                    "categoryName" : "Gin",
                    "minimumPrice" : 100.00,
                    "currentPrice" : 150.00,
                    "itemPhoto" : "www.dealingroom.com/public/img/hendricks.jpeg",
                    "itemDescription" : "A superb, and utterly unique, pink-tinged gin from William Grant's. Infused with rose petals and cucumber as well as the normal botanicals, this is a must for all gin-lovers. In the summertime, Hendrick's makes a fantastically refreshing gin and tonic: serve in a tall glass with plenty of ice and garnish with thinly-sliced cucumber – delicious!"
                }            
            }
        ]

### Adding new item [POST]
You can add additional items into the database using this action. It takes a JSON
object containing:
- itemName
- itemStock
- minimumPrice
- itemPhoto
- itemDescription

+ Request (application/json)

        {
            "itemName": "Heineken",
            "itemStock": 100,
            "minimumPrice": 45.00,
            "itemPhoto": "www.dealingroom.com/public/02/img/heineken.jpeg",
            "itemDescription": "100% Barley malt, choice hops and pure water give this brew unsurpassed clarity."
        }

+ Response 201

## %5Bapi/items/?categories=""%5D [/api/items/?categories=""]
### Obtaining all item's information within a category [GET]
+ Response 200 (application/json)

        [
            "categoryName": "Beer"
            "categoryPhoto": "categoryPhoto":"www.dealingroom.com/public/img/beer.jpeg"
            {
                "id": 1,
                "itemName": "Asahi",
                "itemStock": 100,
                "categoryName": "Beer",
                "minimumPrice": 50.00,
                "currentPrice": 105.00,
                "itemPhoto": "www.dealingroom.com/public/img/asahi.jpeg",
                "itemDescription": "Asahi Super Dry was a direct result of extensive market research which indicated a consumer preference for a more palatable beer with less maltiness, relatively high alcohol content and a light aftertaste, that paired well with the changing Japanese diet. With this insight Asahi used its brewing knowledge to develop a beer with a crisp bite, refreshing taste and clear finish to satisfied this requirement."
            },
            {
                "id": 2,
                "itemName": "Heineken",
                "itemStock": 100,
                "categoryName": "Beer",
                "minimumPrice": 45.00,
                "currentPrice": 90.00,
                "itemPhoto": "www.dealingroom.com/public/img/heineken.jpeg",
                "itemDescription": "100% Barley malt, choice hops and pure water give this brew unsurpassed clarity."
            },
            {
                "id": 3,
                "itemName": "Peroni",
                "itemStock": 100,
                "categoryName": "Beer",
                "minimumPrice": 55.00,
                "currentPrice": 10.00,
                "itemPhoto": "www.dealingroom.com/public/img/Peroni.jpeg",
                "itemDescription": "The original Italian lager. Peroni is the number one lager brand in Italy and has been for over one and a half centuries. This premium, clear, golden-yellow lager, with 4.7 ABV, is the result of the dedication to brewing of generations of the most qualified braumeisters."
            },
            {
                "id": 4,
                "itemName": "Stella Artois",
                "itemStock": 100,
                "categoryName": "Beer",
                "minimumPrice": 60.00,
                "currentPrice": 100.00,
                "itemPhoto": "www.dealingroom.com/public/img/stellaartois.jpeg",
                "itemDescription": "Stella Artois is one of the world’s best-selling beers and is enjoyed in more than 80 countries. Its full, characteristic flavour and high quality is assured through a superior brewing process and by using the finest ingredients available."
            }
        ]
    
## %5Bapi/orders/:orderid%5D [/api/orders/:orderid]
### Retreiving order information by order id [GET]
+ Response 200 (application/json)

        {
            "users.id": 1,
            "userName": "John Doe",
            "displayName": "Johnny",
            "orders.id" : 1,
            "table": 11,
            "status": "confirmed",
            {
                "itemName": "Asahi",
                "ice": "normal",
                "sweetness": "normal",
                "garnish" : "normal",
                "purchasePrice" : 105.00
            },
            {
                "itemName": "Grey Goose",
                "ice": "extra",
                "sweetness": "normal",
                "garnish" : "normal",
                "purchasePrice" : 150.00
            }
        }

### Amending order information by id [PUT]
Currently reserved for updating status of orders or to delete orders.
+ Request (application/json)

        {
            "orders.id": 1,
            "status": "made",
            "isActive": true
        }

+ Response 201

## %5Bapi/orders/:userid%5D [/api/orders/:userid]
### Retreiving order information by user id [GET]
+ Response 200 (application/json)

        {
            "users.id": 1,
            "userName": "John Doe",
            "displayName": "Johnny",
            {
                "orders.id" : 1,
                "table": 11,
                "status": "confirmed",
                {
                    "itemName": "Asahi",
                    "ice": "normal",
                    "sweetness": "normal",
                    "garnish" : "normal",
                    "purchasePrice" : 105.00
                },
                {
                    "itemName": "Grey Goose",
                    "ice": "extra",
                    "sweetness": "normal",
                    "garnish" : "normal",
                    "purchasePrice" : 150.00
                }
            },
            {
                "orders.id": 2,
                "table": 11,
                "status": "confirmed",
                {
                    "itemName": "Asahi",
                    "ice": "normal",
                    "sweetness": "normal",
                    "garnish" : "normal",
                    "purchasePrice" : 105.00
                }
            }
        }

### Adding order by user id [POST]
+ Request (application/json)

        {
            "users.id": 1,
            "userName": "John Doe",
            "displayName": "Johnny",
            "table": 11,
            "status": "ordered",
            {
                "itemName": "Asahi",
                "ice": "normal",
                "sweetness": "normal",
                "garnish" : "normal",
                "purchasePrice" : 105.00
            },
            {
                "itemName": "Grey Goose",
                "ice": "extra",
                "sweetness": "normal",
                "garnish" : "normal",
                "purchasePrice" : 150.00
            }
        }

+ Response 201 (application/json)

        {
            "users.id": 1
            "orders.id": 1
        }

## %5Bapi/ordersPrices%5D [/api/ordersPrices/]
### Retreiving all order price information that day [GET]
Used to compile comparison charts for consumptions
+ Response 200 (application/json)

        {
            {
                "beer": 105.00,
                "cocktail": 0,
                "redWine": 0,
                "whiteWine": 0,
                "champagne": 0,
                "vodka": 150.00,
                "tequila": 0,
                "whiskey": 0,
                "gin": 0,
                "rum": 0,
                "brandy": 0,
                "non-alcoholic": 0,
                "snack": 0,
                "main": 0,
                "dessert": 0
            },
            {
                "beer": 130.50,
                "cocktail": 158.50,
                "redWine": 103.00,
                "whiteWine": 90.50,
                "champagne": 121.00,
                "vodka": 160.50,
                "tequila": 92.00,
                "whiskey": 143.00,
                "gin": 102.50,
                "rum": 89.50,
                "brandy": 104.50,
                "non-alcoholic": 36.50,
                "snack": 85.00,
                "main": 104.50,
                "dessert": 48.50
            },
        }